name: Tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            ~/.m2
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Build
        run: SKIP_JAVADOC=true ./gradlew clean assemble testClasses --parallel --stacktrace

      - name: Run tests
        run: |
          ./gradlew test --info --stacktrace --continue \
          --parallel \
          -Drobolectric.alwaysIncludeVariantMarkersInTestName=true \
          -Dorg.gradle.workers.max=2

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test_results
          path: '**/build/test-results/**/TEST-*.xml'

  publish_test_results:
    needs: tests
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Download All Test Results
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts

      - name: Publish All Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'artifacts/**/TEST-*.xml'
